### PR TITLE
Product service

### PR DESCRIPTION
**Pull request by michloj571**

### CODE REVIEW

**Comment by karolinak00** [comment]
For me looks good.

**Comment by karolinak00** [comment]
For me looks good, but I've got one question. Why did you change entity names?

**Comment by michloj571** [comment]
> Why did you change entity names?
I've noticed that the annotations were misused, as we've specified a table name instead of the entity's name

**Comment by MrChrisFix** [comment]
Requests for raports should be POST, since we need the body when we sometimes want to get raports in a specific time window. I guess we made an error in the discord api listing

**Comment by MrChrisFix** [comment]
Another thing that (I think) is missing is the endpoint for getting/uploading images (we talked about it on discord)

**Comment by michloj571** [comment]
> Requests for raports should be POST, since we need the body when we sometimes want to get raports in a specific time window. I guess we made an error in the discord api listing

Done

**Comment by michloj571** [comment]
> Missing: POST request /product/price - for searching by price(min, max) and category

These two endpoints will be added today

**Comment by michloj571** [comment]
> Missing: POST request /product/price - for searching by price(min, max) and category

An endpoint for listing by category is already added

**Comment by MrChrisFix** [comment]
> > Missing: POST request /product/price - for searching by price(min, max) and category
> 
> An endpoint for listing by category is already added

I ment one POST request, where I can get products by price AND category (since we are showing products only based on the selected category)

**Comment by michloj571** [comment]
> > > Missing: POST request /product/price - for searching by price(min, max) and category
> > 
> > 
> > An endpoint for listing by category is already added
> 
> I ment one POST request, where I can get products by price AND category (since we are showing products only based on the selected category)

Done

**Pull request merged**
